sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
before_install:
    - sudo apt-get intall virt-top
    - sudo apt-get install sysstat
    - sudo apt-get install git
install:
    - npm install
script:
    - npm test